### ISSUE TITLE
usWeightclass

### ISSUE THREAD

**Issue by RosaWagner** [huertatipografica/piazzolla#10]
So I saw in the source file, you adjusted the usWeightClass, although now we do prefer Thin=100 and ExtraLight=200 for ttf. So we don't add a custom parameter in the source file and in order to correct the usWeightClass for the OTF, we use a script in the post process. Something like that :

```
otfs=$(ls ../fonts/otf/*.otf)
for otf in $otfs
do
	gftools fix-weightclass $otf
	[ -f $otf.fix ] && mv $otf.fix $otf
done
```

**Comment by juandelperal** [comment]
Perfect, will do it
