### ISSUE TITLE
STAT and issues in InDesign 2020

### ISSUE THREAD

**Issue by juandelperal** [huertatipografica/piazzolla#12]
Hi there
The STAT table as it was in 71725209a6bce7dbb8860ab9d145fc11a42ff489 made some problems in InDesign, which I fixed by adding locations in tools/buildStat.py

Now it works better. But I see two issues:
- Indesign: changing the axes values set the font style to italic:
- Mac Font Book not showing names properly (when I drop the STAT table this problem is solved):

Maybe this is connected with the `elidedFallbackName` parameter in tools/buildStat.py?
```python
buildStatTable(ttFont, axes, locations, 'Italic' if isItalic else 'Upright')
```

@RosaWagner

![STAT issue](https://user-images.githubusercontent.com/2414972/90776071-eaaa8800-e2f9-11ea-960c-16b52a8c80f1.gif)
<img width="398" alt="Screen Shot 2020-08-20 at 15 18 44" src="https://user-images.githubusercontent.com/2414972/90775950-c353bb00-e2f9-11ea-97df-9c046c5bc13e.png">
<img width="402" alt="Screen Shot 2020-08-20 at 15 18 29" src="https://user-images.githubusercontent.com/2414972/90776012-d6ff2180-e2f9-11ea-8de5-c7ef98314bc7.png">

**Comment by juandelperal** [comment]
This seems related to the version of the STAT table:

`table.Version = 0x00010001`
InDesign: Sliders don't work at all

`table.Version = 0x00010002`
InDesign: Sliders work but always switching to Italics

**Comment by m4rc1e** [comment]
I've had the same issues but I've solved them by doing the following:

- Use format 2 AxisValues
- Include nameID 25
- Include psnames for fvar instances

I'll have Roboto Serif up in a few days which you could use as a reference.

**Comment by RosaWagner** [comment]
Hi @juandelperal, I am back from holidays :) where are we in there ? Any improvement on this indesign issue?

**Comment by juandelperal** [comment]
Thanks @RosaWagner 
Yes, I worked a little bit more changing the ital axis tag as here: https://docs.microsoft.com/en-us/typography/opentype/spec/stat#example-5-a-family-comprised-of-a-non-italic-variable-font-plus-an-italic-variable-font and adding ranges in the weight axis.
I also reviewed some fonts that work OK in InDesign and tried to emulate the STAT table, but still there are problems with Piazzolla. (BTW in Illustrator everything is OK 🤦‍♂️).

The `wght` axis –format2, which covers the full range between 100 and 900– works ok.
`nominalValue=400, rangeMinValue=350, rangeMaxValue=450`.

Changing the `opsz` axis –format 1, which has discrete positions– doesn't work well.
`value=14, name='14pt'`

This can be solved by changing the table version: 
`statTable.Version = 0x00010002`
which seems very random.

In any case: moving the sliders switch to italics

——

If you see something to fix please let me know.
For testing/fixing my workflow is:

1. Copying the fonts in `/Library/Application Support/Adobe/Fonts`.
2. Test options in buildStat.py
3. Run 
```bash
for VF in /Library/Application\ Support/Adobe/Fonts/Piazzolla*.ttf; do
    python tools/buildStat.py $VF
done
```

Changes apply instantly.
Thanks

**Comment by juandelperal** [comment]
I also copied some code of @m4rc1e :)
https://github.com/TypeNetwork/Roboto/commit/8fd92361e85f031342493ce6994bf7e5ee6a08f5

**Comment by RosaWagner** [comment]
This bug is so weird ^^ But as Marc says many times, variable font support on indesign is super experimental and will get better in the future. Important is that it works on the web and illustrator. Can you release the last binaries ? I gonna check directly the TTF ;)

**Comment by juandelperal** [comment]
Yes, agree
https://github.com/huertatipografica/piazzolla/releases/latest

Thanks

**Comment by m4rc1e** [comment]
nameID25 should be the following:

Roman:
`PiazollaRoman`

Italic:
`PiazollaItalic`


The fvar instance ps names should be structured:

Roman:
`PiazollaRoman-Bold`

Italic:
`PiazollaItalic-Bold`

Just copy, https://github.com/TypeNetwork/Roboto/blob/master/scripts/gen_stat.py and replace the wdth axis with your opsz axis.

**Comment by thlinard** [comment]
Note that as of InDesign 2020 15.1.12, nameID25 + psnames in fvar is sufficient.

**Comment by juandelperal** [comment]
Thanks @m4rc1e 
Thats what I did. It seems like the name 25 was modified in
https://github.com/huertatipografica/piazzolla/blob/master/tools/fixNameTable.py

By removing that, the names are as you described:

> nameID25 should be the following:
> 
> Roman:
> `PiazollaRoman`
> 
> Italic:
> `PiazollaItalic`
> 
> The fvar instance ps names should be structured:
> 
> Roman:
> `PiazollaRoman-Bold`
> 
> Italic:
> `PiazollaItalic-Bold`
>

**Comment by thlinard** [comment]
> Thanks @m4rc1e
> Thats what I did. It seems like the name 25 was modified in
> https://github.com/huertatipografica/piazzolla/blob/master/tools/fixNameTable.py
> 
> By removing that, the names are as you described:
> 
> > nameID25 should be the following:
> > Roman:
> > `PiazollaRoman`
> > Italic:
> > `PiazollaItalic`
> > The fvar instance ps names should be structured:
> > Roman:
> > `PiazollaRoman-Bold`
> > Italic:
> > `PiazollaItalic-Bold`

Hi @juandelperal 

In v2.000 https://github.com/huertatipografica/piazzolla/releases/latest nameID 25 are the same for Roman and Italic.

**Comment by juandelperal** [comment]
Hi @thlinard 
Thanks, I just removed fixNameTable.py from the chain and 2.001 is building with that fix.

**Comment by thlinard** [comment]
Have you the latest binaries?

**Comment by juandelperal** [comment]
Yes, in 2.001 it's now fixed.
https://github.com/huertatipografica/piazzolla/releases/tag/v2.001

It wasn't related to fixNameTable.py but  https://github.com/huertatipografica/piazzolla/blob/master/tools/buildStat.py. Thanks @m4rc1e

**Comment by thlinard** [comment]
> This bug is so weird ^^ But as Marc says many times, variable font support on indesign is super experimental and will get better in the future. Important is that it works on the web and illustrator.

Not exactly. InDesign supports VF when they are made exactly like the VFs made by Adobe, which is a bit restrictive I must admit. InDesign 15.1.12 is a bit more forgiving.
