### ISSUE TITLE
U+220F N-ARY PRODUCT and U+2211 N-ARY SUMMATION are too short

### ISSUE THREAD

**Issue by dscorbett** [huertatipografica/piazzolla#13]
U+220F N-ARY PRODUCT and U+2211 N-ARY SUMMATION look identical to U+03A0 GREEK CAPITAL LETTER PI and U+03A3 GREEK CAPITAL LETTER SIGMA. _n_-ary operators should descend below the baseline.
![∏∑ΠΣ](https://user-images.githubusercontent.com/1124347/94347632-e3b31b80-0003-11eb-8ee7-9f2a06e70a33.png)

**Comment by juandelperal** [comment]
Thanks @dscorbett por pointing this.
From version v2.002 this is fixed. Will be built and released soon
