### ISSUE TITLE
.woff2 fonts

### ISSUE THREAD

**Issue by bigandy** [huertatipografica/piazzolla#14]
HI there, 

thanks for making an incredible typeface and I am already using via google fonts. Is it possible to provide a .woff2 download so that I can embed it in my site's code rather than via Google fonts? 

Thanks, 

Andrew

**Comment by juandelperal** [comment]
Hi @bigandy 
Thanks! Of course, you can download the font files from https://github.com/huertatipografica/piazzolla/releases/latest

**Comment by bigandy** [comment]
@juandelperal thanks a lot for the link
