### ISSUE TITLE
"fi" ligatures

### ISSUE THREAD

**Issue by RGB-es** [huertatipografica/piazzolla#18]
I can see "ft" and "ff" ligatures, but not "fi" 

![ligatures](https://user-images.githubusercontent.com/7756783/99128778-0331f200-260c-11eb-8fe4-a65c21c172bb.png)

Is this by design? 

Tested with v2.003 in both, XeLaTeX and LibreOffice Writer. 

[BTW, thanks for such an interesting typeface!]

**Comment by RuixiZhang42** [comment]
I&nbsp;think this is by design. To quote Matthew Butterick:

> (Practical Typography, Section&nbsp;*ligatures*) […] The only time ligatures are mandatory is when you have an actual overlap between the letters f and&nbsp;i. […]

If the overhanging shape of&nbsp;f does not collide with the next letter, then ligatures are completely optional. In this case, ligatures can actually be more distracting. BTW, the `ft` and `ff` combinations just “look” like ligatures.

**Comment by juandelperal** [comment]
Hi! 
Yes. This is the design. Exactly as @RuixiZhang42 described. 
Sorry for the delay
