### ISSUE TITLE
Named instances

### ISSUE THREAD

**Issue by juandelperal** [huertatipografica/piazzolla#2]
In Piazzolla we have a opsz range between 8 and 30. The idea is to set **Text** (size 14) and **Big** (size 30) instances and maybe using that names in the menu. Is that possible or should I use something like **14pt Semibold**?
IMHO including number seems too much specific and less user friendly, but it is just an opinion.

So, how will be the main (default) instance named? The old "Regular" should now be called "30pt Regular" and the family would be released without any style named "Regular"?
I updated the names like this, but I am not sure if it's OK.

<img width="830" alt="Opt 1" src="https://user-images.githubusercontent.com/2414972/79120490-505a9680-7d93-11ea-96a5-91cd69f3d194.png">

**Comment by juandelperal** [comment]
I added a STAT table with 

- 3 optical sizes (Micro, Text, Big)
- 9 weights (100…900)
- 2 Italic positions (Upright Italic)

But less named instances:

- 9 weights in the Big `opsz`
- 7 weights in the Text `opsz` (no Thin nor Black)

It seems logic to me, I made a release with the files, just in case you want to take a look, the binaries are in
https://github.com/huertatipografica/piazzolla/releases/tag/v1.000

**Comment by davelab6** [comment]
Optical sizes can't be named with arbitrary and imprecise labels, they must
specifically state their point size.

**Comment by m4rc1e** [comment]
Agree with Dave. This was the only issue i found reviewing #3. Change the opsz stat entries to pt and we're good.

**Comment by juandelperal** [comment]
OK, in that case the ranges does not have any sense here, right?
https://github.com/huertatipografica/piazzolla/blob/master/sources/Piazzolla.stylespace

Do you have a released or unreleased GF family with opsz and named instances sorted in a proper way?

**Comment by m4rc1e** [comment]
Just rename:

micro = 8pt
text = 14pt
big = 30pt

**Comment by yanone** [comment]
I’m taking care of this atm

**Comment by davelab6** [comment]
How did you determine the pt size?

**Comment by juandelperal** [comment]
@yanone thanks for your PR #4, 
I already merged it, it is good for static, but not for variable, as now the named instances are repeated three times (within the same family name).
I will work on it.

I attach some examples of this:
<img width="205" alt="Screen Shot 2020-07-17 at 15 26 45" src="https://user-images.githubusercontent.com/2414972/87792092-ae3fc400-c843-11ea-8fc7-58dbf5fd85ac.png">

<img width="257" alt="Screen Shot 2020-07-17 at 15 39 41" src="https://user-images.githubusercontent.com/2414972/87792138-bf88d080-c843-11ea-8300-228938fa9e45.png">

**Comment by yanone** [comment]
Sure, feel free to work on it. 
I can say that this hints at naming in the fvar table.

If you run into trouble, please let me know. I'm working for two more weeks now before a longer summer break, so it would be nice to finish this beforehand, and I'll be happy to help anytime.


> Am 17.07.2020 um 15:40 schrieb Juan del Peral <notifications@github.com>:
> 
> 
> @yanone thanks for your PR #4,
> I already merged it, it is good for static, but not for variable, as now the named instances are repeated three times (within the same family name).
> I will work on it.
> 
> I attach some examples of this:
> 
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



--

Yanone
Dipl.-Designer,
Master of Design in Type & Media
https://yanone.de
Twitter/Instagram: @yanone
+49 176 24023268 (Germany)

Type.World project:
https://type.world

Crowd funding on:
https://www.patreon.com/typeWorld

**Comment by yanone** [comment]
Here’s an update: 
Google Fonts currently only allows the standard names for weight + italic as style names, effectively leading to only a base set of instances to be defined and directly accessible through the drop down menu: https://github.com/googlefonts/gf-docs/tree/master/Spec#fvar-instances

Other instances will be accessible by VF savvy applications through the STAT table, where all axes are defined.
You can basically only choose which optical size you want defined as instances, no more.

So I can finish this up if you wish.

**Comment by juandelperal** [comment]
Ah, great, I see. I didn't check that document for a while. It seems logic

I was working on something like this:
https://github.com/huertatipografica/piazzolla/compare/naming#diff-30abf089d728037f636e6f9b6316880a

but it won't work

—
So I will drop all the named instances that don't correspond to 30pt and add the `ElidableAxisValueName` flag to 30pt, so that the fvar instance names match the static fonts.
