### ISSUE TITLE
Lowercase Cyrillic letter /л

### ISSUE THREAD

**Issue by StefanPeev** [huertatipografica/piazzolla#20]
Lowercase Cyrillic letter **/л** is unusual for Bulgarians, and certainly for Russians. On the other hand, the capital Cyrillic letter **/Л** and the lowercase Cyrillic letter **/л** diverge as a construction, which is inappropriate.

**Comment by juandelperal** [comment]
Hi Stefan
I attach both the "normal" and Bulgarian versions of л. 
Could you provide a screenshot to illustrate the divergence?

![image](https://user-images.githubusercontent.com/2414972/110600263-09804700-8184-11eb-8611-36598f873815.png)

**Comment by juandelperal** [comment]
Hi @StefanPeev 
Thanks for pointing this issue. It has been fixed a long time ago. 
I submitted a pull request on google fonts with this and many other improvements.
https://github.com/google/fonts/pull/2804

I will also send you an email.
Have a nice weekend

**Comment by juandelperal** [comment]
(you can download the latest version from this repo. Google fonts team will merge the change soon)
