### ISSUE TITLE
Consider type.today's Cyrillic review

### ISSUE THREAD

**Issue by thlinard** [huertatipografica/piazzolla#21]
https://type.today/en/journal/old-style#Piazzolla

**Comment by juandelperal** [comment]
Thanks, Thomas, great to read the review. 
I will write them since the static contours are already merged :)

<img width="865" alt="Screen Shot 2021-08-06 at 16 10 28" src="https://user-images.githubusercontent.com/2414972/128523242-a03525ab-3f39-47cc-bfd7-7838349381aa.png">

**Comment by thlinard** [comment]
Hi @juandelperal 

It's good for the statics, but their criticism of the size of the breve seems relevant, what do you think?

For what they say about the different width between Latin and Cyrillic symbols, I haven't been able to replicate their example.
