### ISSUE TITLE
Dots and diacritics (sometimes?) export as × in PDFs from InDesign 2022?

### ISSUE THREAD

**Issue by kokoshneta** [huertatipografica/piazzolla#24]
I’m guessing this is probably ultimately an issue with InDesign’s variable font handling (notoriously tricky), but it may be something that can be fixed with a fix in the font, and if so, that will probably be a lot faster than waiting for Adobe to implement a bug fix (’cause that doesn’t happen overnight).

This issue does not seem to happen in InDesign 2021, but it happens in InDesign 2022, at least sometimes. It somehow managed to fix itself on my desktop earlier today after I tried to make a clean file for testing purposes, but now it also happens on my laptop.  It occurs when exporting the document to PDF – I’ve tried various export presets (only print, though), and it seems to occur in all of them.

Essentially, what happens is that diacritics, as well as the top-most dot in various glyphs are exported as very thin ×-like crosses that appear on the baseline on top of previous letters. By ‘top-most dot’, I mean the dot over i and j, as well as the upper (but not the lower) dot in a colon or semicolon, etc.

Here is an example screenshot from such an InDesign document:
<img width="1033" alt="Text in InDesign" src="https://user-images.githubusercontent.com/21343099/146275289-e56ee3ac-7e6d-4544-a1bf-d0e34f1eadb9.png">

And here is the same bit from a PDF exported with the [High Quality Print] preset:
<img width="1105" alt="Text in PDF" src="https://user-images.githubusercontent.com/21343099/146275370-c31a9b2c-c6f1-4035-bfa6-28fdf96420ab.png">

The dots over the i’s, the acute accent in _café_ and the cedilla in _façade_ can clearly be seen as odd crosses on top of the preceding letters.

Is it possible to tell from this what is causing this error, and is there a way to quickly fix it by tweaking something in the font itself?

_Note:_ This doesn’t seem to happen with the italic variants, only regular.

Attached file:
[Test.zip](https://github.com/huertatipografica/piazzolla/files/7723144/Test.zip) (InDesign document + PDF file)

**Comment by kokoshneta** [comment]
This is all with the variable font downloaded straight from the GitHub page, not the Google Fonts versions. I haven’t tested with those.

**Comment by kokoshneta** [comment]
It’s now been confirmed by another user (on Windows; I’m on a Mac) that the issue is also present with the Google Fonts version of the font.

**Comment by juandelperal** [comment]
Hi @kokoshneta 
I have an old version of InDesign. Could you please include a IDML file?

Thanks

**Comment by kokoshneta** [comment]
@juandelperal
Of course – [here you go](https://github.com/huertatipografica/piazzolla/files/7726530/Test.idml.zip). I’m not sure it’ll help much, though, since the issue only appears in InDesign 2022. At least in ID2021, everything exports correctly, so if you have an older version, there’s a good change you won’t be able to see the bug at all when you export.

**Comment by juandelperal** [comment]
I could open and export the pdf. Everything worked OK in InDesign 15.0.1
The only thing that caught my eye is that the name of the font is different:

![image](https://user-images.githubusercontent.com/2414972/146357706-10a69844-b779-4c0e-9751-91b2a634e117.png)

Please make sure you're using the original font (the one you can download from this repository) and not another version or subset.

Let me know

**Comment by kokoshneta** [comment]
As I said in the first post, I am using the font downloaded from this repository.

I get the message you’re seeing there if I _delete_ the font downloaded from the repository and _install_ the Google Fonts version, but only then.

But yes, in InDesign 15 (2020), everything works as expected. Also in InDesign 16 (2021). The bug is only present in InDesign 17 (2022).

**Comment by kokoshneta** [comment]
A breakthrough!

The other user who’s been testing with me has discovered that the bug depends on the optical size axis.

If you choose one of the predefined weights (Thin, Light, Regular, Bold, etc.), then the optical size is set to the maximum (30) by default and exporting to PDF works fine – no weird artefacts.

If you then manually change the optical size axis to anything other than 30 – or if you change the font size and let InDesign automatically adjust the optical size accordingly (this is a new feature in InDesign 17 [2022]) – then the PDF displays the artefacts.

So it looks like it’s a bug specifically in how InDesign 17 (2022) handles the optical size axis in the font: only the value 30 works properly.

**Comment by kenmcd** [comment]
> Essentially, what happens is that diacritics, as well as the top-most dot in various glyphs are exported as very thin ×-like crosses that appear on the baseline on top of previous letters. By ‘top-most dot’, I mean the dot over i and j, as well as the upper (but not the lower) dot in a colon or semicolon, etc.

Looks like it (InDesign) has an issue with components.
In each case it is losing the first component, the upper dots, the cedilla ...
and it is replacing them with the .notdef symbol - which is a large X in this font (which is quite odd).

@juandelperal Adding to the confusion is an interpolation error in the .notdef glyph. Note the pointed ends in the image above. This is from an interpolation error caused by wrong contour directions in the Light master. 
(EDIT - s/b Thin master).

**Comment by kokoshneta** [comment]
@kenmcd Thanks for the extra info! The InDesign bug – it has been confirmed to be a bug – is seemingly also related to a lot of others that have been reported. Someone posted a long list of related reports elsewhere:

- [Umlauts generate small square after export](https://community.adobe.com/t5/indesign-discussions/umlauts-generate-small-square-after-export/m-p/12542323#M454655)
- [Can't export quotation marks in an open source font to PDF](https://community.adobe.com/t5/indesign-discussions/can-t-export-quotation-marks-in-an-open-source-font-to-pdf/td-p/12546830)
- [Export to pdf destroys font](https://community.adobe.com/t5/indesign-discussions/export-to-pdf-destroys-font/m-p/12547575#M455019)
- [Plairfay display font is giving troubles](https://community.adobe.com/t5/indesign-discussions/plairfay-display-font-is-giving-troubles/m-p/12631169#M459814)
- [Problème police](https://community.adobe.com/t5/indesign-discussions/probl%C3%A8me-police/m-p/12568514#M456312)
- [Quote marks displaying incorrectly in exported PDF from InDesign](https://community.adobe.com/t5/indesign-discussions/quote-marks-displaying-incorrectly-in-exported-pdf-from-indesign/m-p/12572502#M456513)
- [Italicized semicolons not exporting into pdf!](https://community.adobe.com/t5/indesign-discussions/italicized-semicolons-not-exporting-into-pdf/m-p/12574173#M456628)
- [Colons changing to squares when exporting to PDF from InDesign](https://community.adobe.com/t5/indesign-discussions/colons-changing-to-squares-when-exporting-to-pdf-from-indesign/m-p/12583002#M457259)
- [Black Lines Appear After PDF Export](https://community.adobe.com/t5/indesign-discussions/black-lines-appear-after-pdf-export/m-p/12602721#M458378)
- [PDF-error in Font "Lora"](https://community.adobe.com/t5/indesign-discussions/pdf-error-in-font-quot-lora-quot/m-p/12601086#M458223)
- [Strange rectangles appear exporting the document](https://community.adobe.com/t5/indesign-discussions/strange-rectangles-appear-exporting-the-document/td-p/12632967)
- [Character appearing as squares in PDF](https://community.adobe.com/t5/indesign-discussions/character-appearing-as-squares-in-pdf/m-p/12633538#M459964)
- [Blank box over colon when exporting PDF from Indesign](https://community.adobe.com/t5/indesign-discussions/blank-box-over-colon-when-exporting-pdf-from-indesign/td-p/12640362)

This doesn’t say anything about the interpolation error in the Light master, which I assume is something that needs to be fixed within Piazzolla development; but the bug has been confirmed by Adobe and will be fixed in an upcoming point-update.

**Comment by kenmcd** [comment]
> @kenmcd Thanks for the extra info! The InDesign bug – it has been confirmed to be a bug – is seemingly also related to a lot of others that have been reported. Someone posted a long list of related reports elsewhere:

Wow, that is quite a list.
It appears to also happen with static fonts.

One work-around is to use the static OpenType-PS (OTF) fonts.
Those fonts do not have components, so they should not have the issues.
So if you can, un-install the variable TTF fonts, and install the static OTF fonts.
That will work until Adopy fixes InDesign.

And, yes, the interpolation error needs to be fixed in the variable font(s).
That does not affect this issue other than looking a bit odd.

**Comment by kokoshneta** [comment]
Just saw this is still open – the bug was fixed long ago, in InDesign 17.1.
